#!/bin/bash
set -e

# Ensure we are in the sdk root or handle paths correctly
# This script assumes it's run from the cli/elixir-sdk directory or we can find the schema relative to it.

SCHEMA_PATH="../../apps/docs/public/api-reference.json"
TEMP_DIR=".openapi-temp"
TYPES_OUTPUT_DIR="lib/unsent/model"

echo "Generating Elixir types from ${SCHEMA_PATH}..."

# check if schema exists
if [ ! -f "$SCHEMA_PATH" ]; then
    echo "Error: Schema file not found at $SCHEMA_PATH"
    exit 1
fi

# Check if pnpm is available
if ! command -v pnpm &> /dev/null; then
    echo "Error: pnpm not found. Please install Node.js and pnpm."
    exit 1
fi

# Clean up temp directory if it exists
rm -rf "$TEMP_DIR"

# Generate Elixir client using openapi-generator-cli to temp directory
# We only want the models
pnpm dlx @openapitools/openapi-generator-cli generate \
  -i "$SCHEMA_PATH" \
  -g elixir \
  -o "$TEMP_DIR" \
  --global-property models,modelDocs=false,modelTests=false \
  --additional-properties=packageName=unsent,moduleName=Unsent

# Find generated models directory
MODELS_DIR=""
if [ -d "$TEMP_DIR/lib/unsent_api/model" ]; then
    MODELS_DIR="$TEMP_DIR/lib/unsent_api/model"
elif [ -d "$TEMP_DIR/lib/unsent/model" ]; then
    MODELS_DIR="$TEMP_DIR/lib/unsent/model"
else
    echo "Error: Could not find generated models. Expected locations:"
    echo "  - $TEMP_DIR/lib/unsent_api/model"
    echo "  - $TEMP_DIR/lib/unsent/model"
    echo ""
    echo "Directory structure:"
    find "$TEMP_DIR" -type d -maxdepth 4
    exit 1
fi

# Consolidate all types into a single types.ex file
TYPES_FILE="lib/unsent/types.ex"
rm -f "$TYPES_FILE"

echo "# NOTE: This file is auto generated by OpenAPI Generator 7.18.0 (https://openapi-generator.tech)." > "$TYPES_FILE"
echo "# Do not edit this file manually." >> "$TYPES_FILE"
echo "" >> "$TYPES_FILE"

# Process each generated file
for file in "$MODELS_DIR"/*.ex; do
    if [ -f "$file" ]; then
        # Extract module name and content
        # Replace UnsentAPI.Model with Unsent.Types
        # Remove UnsentAPI.Deserializer references and deserialize calls
        sed -e '1,3d' "$file" | \
        sed 's/UnsentAPI\.Model\./Unsent.Types./g' | \
        sed 's/defmodule UnsentAPI\.Model\./defmodule Unsent.Types./g' | \
        sed '/alias UnsentAPI\.Deserializer/d' | \
        sed 's/|> Deserializer\.deserialize([^)]*)//' | \
        sed '/^\s*$/!b; N; /^\s*\n\s*$/d' \
        >> "$TYPES_FILE"
    fi
done

echo "" >> "$TYPES_FILE"
echo "Consolidated $(ls -1 "$MODELS_DIR"/*.ex 2>/dev/null | wc -l | tr -d ' ') type modules into types.ex"

# Cleanup
rm -rf "$TEMP_DIR"

echo ""
echo "✓ Types generated at lib/unsent/types.ex"
